#!/bin/bash

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h | --help )
            echo "Uso: $0 [OPÇÕES] comando1 comando2 ..."
            echo "Opções:"
            echo "  -h, --help           Exibir esta mensagem de ajuda"
            echo "  -d, --detailed       Modo detalhado"
            echo "  -e, --exclude DIR    Excluir diretório da busca"
            exit 0
            ;;
        -d | --detailed )
            detailed_mode=true
            shift
            ;;
        -e | --exclude )
            if [[ -z "$2" || ! -d "$2" ]]; then
                echo "Diretório inválido para exclusão."
                exit 1
            fi
            exclude_dirs+=("$2")
            shift 2
            ;;
        * )
            command_name="$1"
            command_path=$(which "$command_name" 2>&1)  # Redireciona stderr para stdout
            home_command_path="$HOME/$command_name"

            found=false
            for dir in "${exclude_dirs[@]}"; do
                if [[ "$home_command_path" == *"$dir"* ]]; then
                    found=true
                    break
                fi
            done

            if [[ "$command_path" == "no $command_name in"* || "$command_path" == *"no $command_name in"* ]]; then
                command_path=""
            fi

            if [ -n "$command_path" ]; then
                echo "O comando '$command_name' está localizado em: $command_path"
            elif [[ -e "$home_command_path" && "$found" == "false" ]]; then
                echo "O arquivo '$command_name' está localizado em: $home_command_path"
            else
                echo "Comando ou arquivo '$command_name' não encontrado."
            fi

            if [[ "$detailed_mode" == "true" && -n "$command_path" ]]; then
                echo "Detalhes:"
                ls -l "$command_path"
            fi

            shift
            ;;
    esac
done
